version: 2.1
orbs:
  ruby: circleci/ruby@1.1.0

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.1
    executor: ruby/default
    steps:
      - checkout
      - ruby/install-deps
      # - node/install-packages:
      #     pkg-manager: yarn
      #     cache-key: "yarn.lock"
      # - run:
      #     name: Wait for DB
      #     command: dockerize -wait tcp://localhost:5432 -timeout 1m
      # - run:
      #     name: Database setup
      #     command: bundle exec rails db:schema:load --trace
      # # Run rspec in parallel
      - run:
          name: Run tests
          command: bundle exec rails test
      # - ruby/rubocop-check

